/**
 * Next.js Host Bridge — middleware injection.
 *
 * Provides utilities for injecting the OD bridge script into a Next.js
 * project's middleware chain. This allows the OD daemon to communicate
 * with the running Next.js app via middleware-injected headers and
 * cookies.
 *
 * In the Tauri bridge, native IPC handles communication. In the Next.js
 * bridge, we use a combination of:
 *   1. Daemon API routes for command/control (REST)
 *   2. SSE for real-time events (file changes, run status)
 *   3. Middleware injection for OD context headers
 */

/** Configuration for OD middleware injection. */
export interface OdMiddlewareConfig {
  /** The daemon's base URL (e.g., http://localhost:3210). */
  daemonBaseUrl: string;
  /** The OD project ID for the current project. */
  projectId: string;
  /** Optional session token for authenticated requests. */
  sessionToken?: string;
}

/**
 * Build the headers that the OD middleware should inject into responses.
 *
 * These headers allow the Next.js app's client-side code to discover
 * the OD daemon and communicate with it.
 */
export function buildOdInjectionHeaders(config: OdMiddlewareConfig): Record<string, string> {
  const headers: Record<string, string> = {
    'X-OD-Daemon-Url': config.daemonBaseUrl,
    'X-OD-Project-Id': config.projectId,
  };

  if (config.sessionToken) {
    headers['X-OD-Session-Token'] = config.sessionToken;
  }

  return headers;
}

/**
 * Generate a snippet of Next.js middleware code that injects OD headers.
 *
 * This can be used by the daemon to auto-generate or modify a Next.js
 * project's `middleware.ts` file to include OD context headers in every
 * response. The user can also manually add this code.
 */
export function generateMiddlewareSnippet(config: OdMiddlewareConfig): string {
  return `import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

// Open Design middleware — injects OD context headers into responses.
// Auto-generated by @open-design/host-nextjs
export function middleware(request: NextRequest) {
  const response = NextResponse.next();

  // OD daemon connection headers
  response.headers.set('X-OD-Daemon-Url', '${config.daemonBaseUrl}');
  response.headers.set('X-OD-Project-Id', '${config.projectId}');
  ${config.sessionToken ? `response.headers.set('X-OD-Session-Token', '${config.sessionToken}');` : '// No session token configured'}

  return response;
}

export const config = {
  // Apply to all routes except static assets and Next.js internals
  matcher: ['/((?!_next/static|_next/image|favicon.ico).*)'],
};
`;
}

/**
 * Read OD injection headers from the current page's response headers.
 *
 * This is used client-side to discover the OD daemon URL and project ID
 * that were injected by the Next.js middleware.
 */
export function readOdInjectionHeadersFromMeta(): OdMiddlewareConfig | null {
  if (typeof document === 'undefined') return null;

  const daemonUrl = document.querySelector('meta[name="x-od-daemon-url"]')?.getAttribute('content');
  const projectId = document.querySelector('meta[name="x-od-project-id"]')?.getAttribute('content');
  const sessionToken = document.querySelector('meta[name="x-od-session-token"]')?.getAttribute('content');

  if (!daemonUrl || !projectId) return null;

  return {
    daemonBaseUrl: daemonUrl,
    projectId,
    ...(sessionToken ? { sessionToken } : {}),
  };
}
